version: "2.2"

services:
 # Spring Boot Application
 spring-app:
  image: fayezz/gestion-station-ski-1.0:latest
  container_name: spring-app-container
  ports:
   - "8085:8085"
  environment:
   - SPRING_DATASOURCE_URL=jdbc:mysql://fayez:3306/devops
   - SPRING_DATASOURCE_USERNAME=root
   - SPRING_DATASOURCE_PASSWORD=
  depends_on:
   - localhost
  networks:
   - mynetwork

 # MySQL Database
 fayez:
  image: mysql:8.0
  container_name: devops
  environment:
   - MYSQL_ALLOW_EMPTY_PASSWORD=yes
   - MYSQL_DATABASE=devops
  ports:
   - "3306:3306"
  volumes:
   - mysql-data:/var/lib/mysql
  networks:
   - mynetwork

networks:
 mynetwork:
  driver: bridge

volumes:
 mysql-data: